### ISSUE TITLE
Sticky search

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/community-repositories#15]
I'd expect the package search in https://sabayon.github.io/community-website/ to be sticky. That is, visible even after scrolling down.

Background:
After reading <q>Start to search on the top bar</q> in **Website usage** I wondered which search. It was out of my viewport at this point.

Ideally the search would be contained in the main navigation. I'll investigate that.

**Comment by mudler** [comment]
Thanks for pointing those issues out, but it would be better to use https://github.com/Sabayon/community-website 's issue system instead of community-repositories (which is for repositories definition files)

**Comment by Ryuno-Ki** [comment]
Would be handy to have repository descriptions here on GitHub to avoid confusion ;-)

Anyway, I opened a ticket over there and close this one here.
