### ISSUE TITLE
Inform user via blackboard

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/community-repositories#16]
A few weeks ago, I was surprised that Telegram (an instant messenger) was removed from the repositories.

This evening, @optiz0r told me that it moved to [SCR](https://wiki.sabayon.org/index.php?title=En:Sabayon_Community_Repositories).

I would expect to get an info after the next `equo update`. @joostruis offered to put a notice on the blackboard if someone else writes the text.

**Comment by optiz0r** [comment]
@joostruis first-draft text for repo noticeboard.

> Some unofficial packages have been moved from the sabayonlinux.org and sabayon-weekly repositories to the Sabayon Community Repositories project (SCR). If a package you need is no longer available in the official entropy repositories, you can search for them in the SCR here: https://sabayon.github.io/community-website/ where you'll also find usage instructions.
> 
> For more information on the SCR, please see our wiki: https://wiki.sabayon.org/index.php?title=En:Sabayon_Community_Repositories

**Comment by mudler** [comment]
message is there :beers:
