### ISSUE TITLE
Responsive search

### ISSUE THREAD

**Issue by Ryuno-Ki** [Sabayon/community-repositories#17]
@optiz0r said on IRC that he would the search bar to give some feedback visually when she's in progress.

The location should be updated with an fragment, like `#app-misc/example-search` and be cached for subsequent requests.

Some questions come to my mind here:
- When to start querying the backend (how many characters need to got typed in? Should the next one be delayed? Imagine users correcting them or typing in quickly)
- For how long should the result be cached? What invalidates it? How is the client/browser informed about the invalidation?
- How should the feedback look like? Can we estimate the time to an reply? (Probably not due to network latency)

**Comment by optiz0r** [comment]
I was thinking more along the lines:
- When you start typing into the search box, a spinner appears to show an ajax request is in progress
- When the ajax returns, if there are no results found, a message/icon showing such.

With regards to deep linking, if I search for a package and find one and click on it, I want to be able to give someone a link that gives them the install instructions directly, as if they'd searched for and clicked on the result. Could be achieved with history api and deep-linking.

Caching may be necessary to avoid ajax load, not something I've put much thought into yet.

**Comment by Ryuno-Ki** [comment]
I was rather thinking on Web Workers for caching. It can store the result for offline usage.

Do we have a template for deep linked sites yet? My trial showed up a modal …
Something like https://packages.sabayon.org/ maybe?

**Comment by optiz0r** [comment]
This issue was moved to Sabayon/community-website#2
